[metadata]
name = sembridge
version = 0.1.0
description = Semantic bridge initialization for transferring sparse encoder embeddings across tokenizers.
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    Intended Audience :: Developers

[options]
packages = find:
python_requires = >=3.8
install_requires =
    torch
    transformers>=4.0.0
    datasets
    entmax
    fastdist
    requests
    numpy
    numba
    scipy
    tqdm
    print-on-steroids
    sentence-transformers

zip_safe = True

[options.extras_require]
dev =
    pytest

[options.packages.find]
exclude =
    tests
